
block # list item
line # vs list
grid / board
tree
chain / web / net

board of blocks
pair?
pointing to

Pointing refers to the graph drawing.
But maybe there is a better way to visualize it? Maybe "watching".

sup(E)=−∞  and inf(E)=+∞

supremum is the first block in the relation, so for numbers it's negative infinity
infinitum is the last block in the relation, so positive infinity

The infimum of a subset S of a partially ordered set P, assuming it exists, does not necessarily belong to S. If it does, it is a minimal or least element of S. Similarly, if the supremum of S belongs to S, it is a maximal or greatest element of S

1 [2 3 4] 5 6 // no minimal element
[1 2 3 4] 5 6 // minimal element

However, the definition of maximal and minimal elements is more general. In particular, a set can have many maximal and minimal elements, whereas infima and suprema are unique.

As an example, in the collection

S = {{d, o}, {d, o, g}, {g, o, a, d}, {o, a, f}}
ordered by containment, the element {d, o} is minimal, the element {g, o, a, d} is maximal, the element {d, o, g} is neither, and the element {o, a, f} is both minimal and maximal. By contrast, neither a maximum nor a minimum exists for S.

https://en.wikipedia.org/wiki/Maximal_element

https://en.wikipedia.org/wiki/Upper_and_lower_bounds

An upper bound is said to be a tight upper bound, a least upper bound, or a supremum if no smaller value is an upper bound. Similarly a lower bound is said to be a tight lower bound, a greatest lower bound, or an infimum if no greater value is a lower bound.

If (L, ≤) is a partially ordered set (poset), and S⊆L is an arbitrary subset, then an element u∈L is said to be an upper bound of S if s≤u for each s∈S. A set may have many upper bounds, or none at all. An upper bound u of S is said to be its least upper bound, or join, or supremum, if u≤x for each upper bound x of S.

A partially ordered set (L, ≤) is called a join-semilattice and a meet-semilattice if each two-element subset {a,b} ⊆ L has a join (i.e. least upper bound) and a meet (i.e. greatest lower bound), denoted by a∨b and a∧b, respectively. (L, ≤) is called a lattice if it is both a join- and a meet-semilattice.

https://en.wikipedia.org/wiki/Join_and_meet

A bounded lattice is a lattice that additionally has a greatest element 1 and a least element 0, which satisfy

0≤x≤1 for every x in L.

https://en.wikipedia.org/wiki/Bravais_lattice
https://en.wikipedia.org/wiki/Fock_space

an infinite array of discrete points
a long line of blocks

# this is an action, so it should be part of the actions on blocks

generated by a set of discrete translation operations described by:

```
\mathbf{R} = n_{1}\mathbf{a}_{1} + n_{2}\mathbf{a}_{2} + n_{3}\mathbf{a}_{3}
```

these blocks each match a pattern:

```coffee
pattern block
  sum from 1, to i
    product
      i integer
      i vector
```

Still not clear what the integer or vector are. How do we draw this?

That vector can be a pointer to the nearest point in the lattice, for example.

https://en.wikipedia.org/wiki/Crystal_system#Classification_of_lattices

Hilbert space is a grid of blocks, where each block has a set of properties. Each block is composed of the same set of internal blocks. Child blocks. Or each block is basically a chunk of blocks, this way you can store this information as a data structure using a line of blocks.

https://en.wikipedia.org/wiki/Hilbert_space

relation inner product
  associates each pair of vectors in the space with a scalar quantity known as the inner product of the vectors
  relation between two vectors

> Inner product spaces generalize Euclidean spaces (in which the inner product is the dot product, also known as the scalar product) to vector spaces of any (possibly infinite) dimension, and are studied in functional analysis.

> Algebraically, it is the sum of the products of the corresponding entries of the two sequences of numbers.

> Apart from the classical Euclidean spaces, examples of Hilbert spaces include spaces of square-integrable functions, spaces of sequences, Sobolev spaces consisting of generalized functions, and Hardy spaces of holomorphic functions.

---

http://english.stackexchange.com/questions/22621/what-are-the-differences-between-inverse-reverse-and-converse

> Original hypothesis: "If I have received $100 in the mail today, I will buy a pair of pants tomorrow."
Converse: "If I buy a pair of pants tomorrow, I have received $100 in the mail today."
Inverse: "If I have not received $100 in the mail today, I will not buy a pair of pants tomorrow."

> The truth or falsehood of the original hypothesis is not equivalent to either the converse or the inverse, but the converse and the inverse are equivalent to each other.

https://en.wikipedia.org/wiki/Approximations_of_%CF%80
https://en.wikipedia.org/wiki/List_of_formulae_involving_%CF%80
